/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.alvin.ui;

import org.alvin.model.ProtocolSettingTableModel;
import craky.componentc.JCButton;
import java.awt.Dimension;

/**
 *
 * @author Administrator
 */
public class ProtocolSettingPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProtocolSettingPanel
     */
    public ProtocolSettingPanel() {
        initComponents();
        jCTable1.setModel(new ProtocolSettingTableModel());
        jButton1.setPreferredSize(new Dimension(80, 21));
        jButton2.setPreferredSize(new Dimension(180, 21));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 =  new JCButton();
        jButton2 =  new JCButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jCTable1 = new craky.componentc.JCTable();

        setLayout(new java.awt.BorderLayout());

        jButton1.setText("Edit");
        jPanel1.add(jButton1);

        jButton2.setText("Reset");
        jPanel1.add(jButton2);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jCTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jCTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private craky.componentc.JCTable jCTable1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
